[package]
name = "sprite_studio"
version = "0.1.0"
authors = ["Kaneyuki Hiromasa <matsugen2511@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.104", features = ["derive"] }
serde-xml-rs = "0.3.1"
failure= "0.1.6"
