[package]
name = "sprite_studio"
version = "0.1.0"
authors = ["Kaneyuki Hiromasa <matsugen2511@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.105", features = ["derive"] }
serde-xml-rs = "0.4.0"
failure= "0.1.7"
log="0.4.8"